default: &default
  adapter: chronomodel
  encoding: unicode
  pool: 20
  username: <%= ENV["POSTGRES_USERNAME"] || 'postgres' %>
  password: <%= ENV["POSTGRES_PASSWORD"] || 'postgres'%>
  host: <%= ENV["POSTGRES_HOST"] || 'localhost' %>

development:
  <<: *default
  database: rundfunk-backend-development

test: &test
  <<: *default
  database: rundfunk-backend-test

fullstack:
  <<: *test

production:
  <<: *default
  database: rundfunk-backend-production
