source 'https://rubygems.org'

gem 'active_model_serializers'
gem 'globalize', github: 'globalize/globalize'
gem 'globalize-accessors'
gem 'cancancan'
gem 'rack-cors', :require => 'rack/cors'
gem 'kaminari'
gem 'scenic'
gem 'pg_search'
gem 'knock'
gem 'valid_email2'


gem 'rails', '~> 5.0', '>= 5.0.0.1'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
#gem 'rails', github: 'rails/rails'

# Use Puma as the app server
gem 'pg'
gem 'puma'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'pry'
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'rspec-json_expectations'
  gem 'rails-controller-testing'
end

group :development do
  gem 'listen'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'capistrano'
  gem 'capistrano-rails'
  gem "capistrano-db-tasks", require: false
  gem 'highline'
end

group :production do
  gem 'rails_12factor'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
