namespace :data do
  desc 'Add `free radio` as a medium category and add all free radios of the Bundesverband'
  task add_new_medium_category_free_radio: :environment do
    freeradio = Medium.create!(id: 4, name_de: 'Freies Radio', name_en: 'Free radio')
    Station.create!(medium: freeradio, name: 'Wüste Welle')
    Station.create!(medium: freeradio, name: 'Radio StHörfunk')
    Station.create!(medium: freeradio, name: 'Radio free FM')
    Station.create!(medium: freeradio, name: 'Radio Dreyeckland')
    Station.create!(medium: freeradio, name: 'Querfunk')
    Station.create!(medium: freeradio, name: 'Freies Radio Wiesental')
    Station.create!(medium: freeradio, name: 'Freies Radio für Stuttgart')
    Station.create!(medium: freeradio, name: 'Freies Radio Freudenstadt')
    Station.create!(medium: freeradio, name: 'bermuda.funk')
    Station.create!(medium: freeradio, name: 'Radio Z')
    Station.create!(medium: freeradio, name: 'Lora München')
    Station.create!(medium: freeradio, name: 'Pi-Radio')
    Station.create!(medium: freeradio, name: 'Onda')
    Station.create!(medium: freeradio, name: 'Radio Słubfurt')
    Station.create!(medium: freeradio, name: 'Freies Sender Kombinat - FSK')
    Station.create!(medium: freeradio, name: 'RundFunk Meißner')
    Station.create!(medium: freeradio, name: 'Radio Unerhört Marburg')
    Station.create!(medium: freeradio, name: 'Freies Radio Kassel')
    Station.create!(medium: freeradio, name: 'LOHRO')
    Station.create!(medium: freeradio, name: 'Radio Flora')
    Station.create!(medium: freeradio, name: 'Punksender')
    Station.create!(medium: freeradio, name: 'Radio Quer')
    Station.create!(medium: freeradio, name: 'Radio T')
    Station.create!(medium: freeradio, name: 'Radio Blau')
    Station.create!(medium: freeradio, name: 'coloRadio')
    Station.create!(medium: freeradio, name: 'Radio Corax')
    Station.create!(medium: freeradio, name: 'Freies Radio Neumünster')
    Station.create!(medium: freeradio, name: 'Freie RadioCooperative Husum')
    Station.create!(medium: freeradio, name: 'Freie Radio - Initiative Flensburg')
    Station.create!(medium: freeradio, name: 'Radio FREI')
  end
end
